version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    target-branch: 'staging'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'deps'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    target-branch: 'staging'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'deps'

  - package-ecosystem: 'pip'
    directory: '/data/src'
    schedule:
      interval: 'weekly'
    target-branch: 'staging'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'deps'
